---
name: "Sets up whatever Fly needs"
description: "Based on the provided inputs, sets up the Fly CLIs"
inputs:
  flyctl-version:
    description: "Set Fly version"
    default: 0.3.194

runs:
  using: "composite"
  steps:
    - uses: superfly/flyctl-actions/setup-flyctl@ed8efb33836e8b2096c7fd3ba1c8afe303ebbff1 # 1.6
      with:
        version: ${{ inputs.flyctl-version }}
