---
name: "Sets up whatever Fly needs"
description: "Based on the provided inputs, sets up the Fly CLIs"
inputs:
  flyctl-version:
    description: "Set Fly version"
    default: 0.3.194

runs:
  using: "composite"
  steps:
    - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # 1.5
      with:
        version: ${{ inputs.flyctl-version }}
