---
name: "Sets up Node's needs"
description: "Based on the provided inputs, sets up the Node environment dependencies"
inputs:
  node-version:
    description: "Node version to use"
    default: "24"

runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org/
        cache: "npm"

    - name: Install npm dependencies
      shell: bash
      run: |
        npm ci
