---
name: "Run the test suite"
description: "Runs the test suite for Ruby apps."
inputs:
  github_token:
    description: "The token used when calling GitHub API"
    required: true
  compile:
    description: "Whether to compile native extensions before running tests"
    required: false
    default: "false"
  coverage:
    description: "Whether to collect coverage information"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run tests
      shell: bash
      run: |
        script/ci || bundle exec rake test
      env:
        COVERAGE: "${{ inputs.coverage }}"

    - name: Install helpers
      if: ${{ inputs.coverage == 'true' }}
      shell: bash
      run: |
        echo "$GITHUB_ACTION_PATH/bin" >> $GITHUB_PATH

    - name: Create coverage report
      if: ${{ inputs.coverage == 'true' }}
      shell: bash
      id: coverage_report
      env:
        NO_COLOR: "1"
      run: |
        coverage_report="$(bundle exec ruby $GITHUB_ACTION_PATH/helpers/report.rb || true)"

        echo "report<<EOF"$'\n'"$coverage_report"$'\n'EOF >> $GITHUB_OUTPUT

    # - name: Post coverage report
    #.  uses: mshick/add-pr-comment@v2
    #   if: "${{ steps.coverage_report.outputs.report != '' }} && ${{ inputs.coverage == 'true' }}"
    #   with:
    #     message: |
    #       <!-- type: code_coverage -->
    #       ## Code coverage

    #       ```
    #        ${{ steps.coverage_report.outputs.report }}
    #       ```
    #     repo-token: ${{ inputs.github_token }}
