name: Localization (I18n)
on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - name: Set up languages
        uses: gjtorikian/actions/setup-languages/ruby@main

      - name: Check (and correct) locale file normalization
        run: bundle exec i18n-tasks normalize

      - name: Check for unused strings
        run: bundle exec i18n-tasks unused

      - name: Check for missing strings in YML
        run: bundle exec i18n-tasks missing

      - name: Check for wrong string interpolations
        run: bundle exec i18n-tasks check-consistent-interpolations

      - name: Commit linted files
        if: always()
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "[auto-lint]: Lint i18n files"
