name: Test cruby build
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      include_musl:
        required: false
        default: false
        type: boolean
      supported_ruby_versions:
        required: false
        default: "3.2,3.3,3.4,4.0"
        type: string

env:
  CACHE_KEY_PREFIX: "cruby-v1"

jobs:
  cruby-package:
    name: Compile native gem
    runs-on: ubuntu-latest
    env:
      SUPPORTED_RUBY_VERSIONS: ${{ inputs.supported_ruby_versions }}
      LATEST_RUBY_VERSION: "4.0"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - x86_64-linux
          - aarch64-linux
          - arm-linux

          - x86_64-linux-musl
          - aarch64-linux-musl

          - x86_64-darwin
          - arm64-darwin

          - x64-mingw-ucrt

        # include musl only when asked
        include_musl:
          - ${{ inputs.include_musl }}
        exclude:
          - include_musl: false
            platform: x86_64-linux-musl
          - include_musl: false
            platform: aarch64-linux-musl

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ruby/setup-ruby@0dafeac902942906541bc140009cdbf32665b601 # v1.315.0
        with:
          ruby-version: "${{ env.LATEST_RUBY_VERSION }}"

      - uses: oxidize-rb/actions/cross-gem@e5f9a49a7812a078584072f6e3f657ad247c8771 # v1.4.4
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: "${{ env.SUPPORTED_RUBY_VERSIONS }}"
          mount-toolchains: "true"

      - name: Display structure of built gems
        run: ls -R
        working-directory: pkg/

      - uses: oxidize-rb/actions/test-gem-build@e5f9a49a7812a078584072f6e3f657ad247c8771 # v1.4.4
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: "${{ env.SUPPORTED_RUBY_VERSIONS }}"
